[package]
name = "sim-device"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
dotenvy = "0.15.7"
rand = "0.9.2"
rumqttc = "0.25.1"
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"